import { useEffect, useState } from 'react'
import { apiClient } from '../api/client'
export default function AttendanceHistory({ lookups }) {
  const [filters, setFilters] = useState({ academic_year: '', term: '', school_class: '', student: '', search: '', date_from: '', date_to: '' })
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  useEffect(() => { let active = true; const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); const timer = setTimeout(() => { setError(''); apiClient(`/school/attendance/history/?${query}`).then((value) => { if (active) setData(value) }).catch(() => { if (active) { setData(null); setError('History could not be loaded. Connect to view saved attendance.') } }) }, 200); return () => { active = false; clearTimeout(timer) } }, [filters])
  const set = (key, value) => setFilters((old) => ({ ...old, [key]: value, ...(key === 'academic_year' ? { term: '' } : {}) }))
  return <section><h2>Attendance History</h2><div className="academic-filters">{[['academic_year', 'Academic Year', lookups.years], ['term', 'Term', lookups.terms.filter((x) => !filters.academic_year || String(x.academic_year) === filters.academic_year)], ['school_class', 'Class', lookups.classes]].map(([key, label, options]) => <label key={key}>{label}<select value={filters[key]} onChange={(e) => set(key, e.target.value)}><option value="">All</option>{options.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}<label>Student search<input value={filters.search} onChange={(e) => set('search', e.target.value)} /></label>{[['date_from', 'From'], ['date_to', 'To']].map(([key, label]) => <label key={key}>{label}<input type="date" value={filters[key]} onChange={(e) => set(key, e.target.value)} /></label>)}{filters.student && <button onClick={() => set('student', '')}>All students</button>}</div>{error && <p role="alert">{error}</p>}{data && <><p>{Object.entries(data.summary).map(([key, value]) => `${key}: ${value}`).join(' ? ')}</p><table className="student-table"><thead><tr><th>Date</th><th>Student</th><th>Class</th><th>Year / Term</th><th>Status</th></tr></thead><tbody>{data.records.map((row) => <tr key={row.id}><td>{row.date}</td><td><button className="text-button" onClick={() => set('student', String(row.student))}>{row.student_name}</button> {row.admission_number}</td><td>{row.class_name}</td><td>{row.academic_year} / {row.term}</td><td>{row.status}</td></tr>)}</tbody></table>{!data.records.length && <p>No saved attendance matches these filters.</p>}</>}</section>
}
