import { validateMoneyForm } from '../components/moneyValidation.js'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiClient } from '../api/client'
import { getFinanceRecords, saveFinanceRecord } from '../api/finance'
import FeeRecordActions from '../components/FeeRecordActions'
import StudentPicker from '../components/StudentPicker'

const blank = { billing_method: 'MONTHLY', name: '', amount: '', academic_year: '', term: '', school_class: null, student: null, is_active: true }
const errorText = (e) => Object.values(e.data || {}).flat().join(' ') || e.message || 'Request failed.'
export default function FeeManagementPage() {
  const [tab, setTab] = useState('Fees')
  const [form, setForm] = useState(blank)
  const [scope, setScope] = useState('school')
  const [student, setStudent] = useState(null)
  const [data, setData] = useState({ structures: [], fees: [], years: [], terms: [], classes: [], charges: [] })
  const [preview, setPreview] = useState(null)
  const [selected, setSelected] = useState('')
  const [fieldErrors, setFieldErrors] = useState({})
  const [filters, setFilters] = useState({ academic_year: '', term: '', fee: '', school_class: '', student: '' })
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  async function load() {
    const [structures, years, terms, classes, charges, fees] = await Promise.all(['recurring-fees', 'academic-years', 'terms', 'classes', 'fee-assignments', 'fees'].map((resource) => getFinanceRecords(resource)))
    setData({ structures, years, terms, classes, charges, fees })
  }
  useEffect(() => { Promise.resolve().then(load).catch((e) => setError(errorText(e))) }, [])
  const set = (key, value) => { setForm((old) => ({ ...old, [key]: value, ...(key === 'academic_year' ? { term: '' } : {}) })); setPreview(null) }
  const term = data.terms.find((x) => String(x.id) === String(form.term))
  async function run(action) { setBusy(true); setError(''); try { await action() } catch (e) { setError(errorText(e)); setPreview(null) } finally { setBusy(false) } }
  async function previewFee(id) { setPreview(await apiClient(`/school/recurring-fees/${id}/preview/`)); setSelected(String(id)); setTab('Fees') }
  async function save(event) {
    event.preventDefault(); if (!validateMoneyForm(event.currentTarget)) return; setFieldErrors({})
    await run(async () => {
      let item
      try { const payload = Object.fromEntries(Object.keys(blank).map((key) => [key, form[key]])); item = await saveFinanceRecord('recurring-fees', payload, form.id) } catch (e) { if (e.data && !e.data.detail && !e.data.non_field_errors) { setFieldErrors(e.data); return } throw e }
      setNotice('Fee structure saved. No charges have been created.'); setForm(blank); setStudent(null); setScope('school'); await load()
      if (item.is_active) await previewFee(item.id)
    })
  }
  const pick = (key, label, options) => <label>{label}<select required value={form[key] || ''} onChange={(e) => set(key, e.target.value)}><option value="">Choose {label.toLowerCase()}</option>{options.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select>{fieldErrors[key] && <span className="form-error">{fieldErrors[key].join(' ')}</span>}</label>
  return <main className="student-page"><header className="student-page-header"><div><Link to="/school/finance">Back to Finance</Link><h1>Fee Management</h1><p>Define fees, select scope, preview obligations and confirm charges.</p></div></header>
    <nav className="academic-filters">{['Fees', 'Charges'].map((name) => <button type="button" key={name} onClick={() => setTab(name)} aria-pressed={tab === name}>{name}</button>)}</nav>
    {error && <p role="alert" className="form-error">{error}</p>}{notice && <p role="status">{notice}</p>}{Object.entries(fieldErrors).filter(([key]) => !['name', 'billing_method', 'amount', 'academic_year', 'term', 'school_class', 'student'].includes(key)).map(([key, errors]) => <p className="form-error" key={key}>{key}: {Array.isArray(errors) ? errors.join(' ') : String(errors)}</p>)}
    {tab === 'Fees' && <><form className="student-form academic-form" noValidate onSubmit={save}><h2>{form.id ? 'Edit Fee' : 'Create Fee'}</h2>
      <label>Billing Method<select value={form.billing_method} onChange={(e) => set('billing_method', e.target.value)}><option value="MONTHLY">Monthly</option><option value="TERMLY">Termly</option><option value="ONE_OFF">One-off</option></select>{fieldErrors.billing_method && <span className="form-error">{fieldErrors.billing_method.join(' ')}</span>}</label>
      <label>Fee Name<input required maxLength="150" value={form.name} onChange={(e) => set('name', e.target.value)} />{fieldErrors.name && <span className="form-error">{fieldErrors.name.join(' ')}</span>}</label>
      <label>{form.billing_method === 'MONTHLY' ? 'Monthly Amount' : form.billing_method === 'TERMLY' ? 'Term Amount' : 'Amount'}<input required type="number" min="0" step="1" value={form.amount} onChange={(e) => set('amount', e.target.value)} />{fieldErrors.amount && <span className="form-error">{fieldErrors.amount.join(' ')}</span>}</label><p>Uses the school’s operational currency.</p>
      <h3>Academic Context</h3>{pick('academic_year', 'Academic Year', data.years)}{pick('term', 'Term', data.terms.filter((x) => String(x.academic_year) === String(form.academic_year)))}
      {term && <p>Term dates: {term.start_date} – {term.end_date}. {form.billing_method === 'MONTHLY' ? `${term.billable_months} billable months ? ${(Number(form.amount || 0) * term.billable_months).toFixed(2)} per fully enrolled learner.` : 'One charge per eligible learner.'}</p>}
      <h3>Scope</h3><label>Scope<select value={scope} onChange={(e) => { setScope(e.target.value); setForm((old) => ({ ...old, school_class: null, student: null })); setStudent(null) }}><option value="school">School-wide</option><option value="class">Class / Grade</option><option value="student">Individual learner</option></select></label>
      {scope === 'class' && pick('school_class', 'Class / Grade', data.classes)}
      {fieldErrors.student && <p className="form-error">Student: {fieldErrors.student.join(' ')}</p>}{scope === 'student' && <StudentPicker required selected={student} onChange={(value) => { setStudent(value); set('student', value?.id || null) }} />}
      <label><input type="checkbox" checked={form.is_active} onChange={(e) => set('is_active', e.target.checked)} /> Active</label>
      <button disabled={busy || (scope === 'student' && !form.student)}>Save and preview</button>{form.id && <button type="button" onClick={() => { setForm(blank); setScope('school'); setStudent(null); setFieldErrors({}) }}>Cancel edit / Create new fee</button>}
    </form><h2>Fees</h2><p>Deactivate keeps the record and stops future use or generation. Delete permanently removes only an unused mistaken setup record and cannot be undone.</p>{data.structures.map((x) => <section className="profile-section" key={x.id}><h3>{x.name}</h3><p>{x.billing_method} · {x.currency} {x.amount} · {x.is_active ? 'Active' : 'Inactive'} ? {data.years.find((y) => y.id === x.academic_year)?.name} / {data.terms.find((t) => t.id === x.term)?.name} ? {x.student ? `Learner #${x.student}` : x.class_name || 'School-wide'}</p>{x.billing_method !== 'LEGACY' && <button onClick={() => { setForm(x); setScope(x.student ? 'student' : x.school_class ? 'class' : 'school'); setStudent(x.student ? { id: x.student, display_name: `Learner #${x.student}` } : null); setFieldErrors({}); setPreview(null) }}>View/Edit</button>}{!x.can_delete && <p>Used fees retain their original terms and amount. Create a new fee to change them.</p>}<FeeRecordActions record={x} recurring onDelete={(id) => apiClient(`/school/recurring-fees/${id}/`, { method: 'DELETE' })} onDeleted={(id) => { setData((old) => ({ ...old, structures: old.structures.filter((item) => item.id !== id) })); setPreview(null); setSelected(''); setNotice('Recurring fee permanently deleted.') }} onDeactivate={async (id, is_active) => { await saveFinanceRecord('recurring-fees', { is_active }, id); setPreview(null); await load() }} />{x.billing_method !== 'LEGACY' && x.is_active && <button disabled={busy} onClick={() => run(() => previewFee(x.id))}>Preview charges</button>}{x.billing_method === 'LEGACY' && <Link to="/school/finance/recurring-fees">Manage legacy monthly schedule</Link>}</section>)}<h2>Existing Fees</h2>{data.fees.map((x) => <section className="profile-section" key={x.id}><h3>{x.name}</h3><p>{x.currency} {x.amount} ? {x.academic_year_name} / {x.term_name}</p><FeeRecordActions record={x} onDelete={(id) => apiClient(`/school/fees/${id}/`, { method: 'DELETE' })} onDeleted={(id) => { setData((old) => ({ ...old, fees: old.fees.filter((item) => item.id !== id) })); setNotice('Fee permanently deleted.') }} onDeactivate={async (id, is_active) => { await saveFinanceRecord('fees', { is_active }, id); await load() }} /></section>)}<Link to="/school/finance/fees">Manage existing fee definitions</Link></>}
    {tab === 'Fees' && preview && <section className="student-form"><label>Fee Structure<select value={selected} onChange={(e) => { setSelected(e.target.value); setPreview(null) }}><option value="">Choose a fee</option>{data.structures.filter((x) => x.is_active && x.billing_method !== 'LEGACY').map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button disabled={busy || !selected} onClick={() => run(() => previewFee(selected))}>Preview</button>
      {preview && <><h2>{preview.name}</h2><p>{preview.academic_year} / {preview.term} · {preview.term_start} – {preview.term_end}</p><p>{preview.billing_method} · {preview.currency} {preview.amount} per period</p><p>{preview.charges_per_student} {preview.billing_method === 'MONTHLY' ? 'billable months' : 'charge'} per fully enrolled learner · {preview.currency} {preview.amount_per_student} full obligation</p><p>Eligible learners: {preview.eligible_students}. Charges to create: {preview.total_charges}. Total value: {preview.currency} {preview.total_value}.</p><p>Learners enrolled for only part of the term are charged only for overlapping periods. Existing charges are excluded from the new total.</p>{preview.periods.map((p) => <p key={p.sequence}>Period {p.sequence}: {p.start} – {p.end}, {p.charges_to_create} new charges</p>)}{preview.missing_enrollments.length > 0 && <details><summary>{preview.missing_enrollments.length} learners lack enrollment records for this year</summary>{preview.missing_enrollments.map((s) => <p key={s.id}>{s.admission_number} · {s.first_name} {s.last_name}</p>)}</details>}<button disabled={busy || !preview.total_charges} onClick={() => run(async () => { const result = await apiClient(`/school/recurring-fees/${selected}/generate-charges/`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirm: true, preview_token: preview.preview_token }) }); setNotice(`${result.assignments_created} charges created.`); setPreview(null); await load() })}>Confirm and generate {preview.total_charges} charges</button></>}
    </section>}
    {tab === 'Charges' && <><div className="academic-filters">{[['academic_year', 'Academic Year', data.years], ['term', 'Term', data.terms.filter((x) => !filters.academic_year || String(x.academic_year) === filters.academic_year)], ['fee', 'Fee', data.fees], ['school_class', 'Class', data.classes]].map(([key, label, options]) => <label key={key}>{label}<select value={filters[key]} onChange={(e) => setFilters((old) => ({ ...old, [key]: e.target.value, ...(key === 'academic_year' ? { term: '' } : {}) }))}><option value="">All</option>{options.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}<label>Student search<input value={filters.student} onChange={(e) => setFilters((old) => ({ ...old, student: e.target.value }))} /></label></div><div className="student-table-wrap"><table className="student-table"><thead><tr>{['Fee / Period', 'Academic Year', 'Term', 'Student', 'Amount'].map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{data.charges.filter((x) => { const fee = data.fees.find((f) => f.id === x.fee); return (!filters.academic_year || String(fee?.academic_year) === filters.academic_year) && (!filters.term || String(fee?.term) === filters.term) && (!filters.fee || String(x.fee) === filters.fee) && (!filters.school_class || (x.historical_class_ids || []).includes(Number(filters.school_class))) && (!filters.student || `${x.student_name} ${x.admission_number}`.toLowerCase().includes(filters.student.toLowerCase())) }).map((x) => <tr key={x.id}><td>{x.fee_name}</td><td>{x.academic_year_name}</td><td>{x.term_name}</td><td><Link to={`/school/finance/students/${x.student}`}>{x.student_name}</Link></td><td>{x.currency} {x.amount_owed}</td></tr>)}</tbody></table></div></>}
  </main>
}
