import { useCallback, useContext, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { downloadHomeworkAttachment, getHomework, saveHomework } from '../api/homework'
import { getAcademicRecords } from '../api/academics'
import { OfflineContext } from '../offline/context'
import { cachedHomework, cacheHomework, homeworkWithLocalChanges, queueHomework } from '../offline/homework'
import { discardOperation, updateOperation } from '../offline/db'

const today = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` }
const blank = () => ({ title: '', instructions: '', school_class: '', subject: '', date_assigned: today(), due_date: '', status: 'draft' })
const message = (error) => Object.values(error?.data || {}).flat().join(' ') || 'The homework could not be saved.'

export default function HomeworkPage() {
  const offline = useContext(OfflineContext)
  const { scope, isReachable, queue = [], refresh, syncNow, syncRevision } = offline ?? {}
  const [data, setData] = useState({ items: [], classes: [], subjects: [] }); const [form, setForm] = useState(blank); const [files, setFiles] = useState([]); const [editing, setEditing] = useState(null); const [filters] = useState({ school_class: '', subject: '', due_date: '', status: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const issues = queue.filter((operation) => operation.module === 'homework' && operation.status === 'failed')
  const load = useCallback(async () => { if (!scope) return; setLoading(true); try { if (isReachable) { const [items, classes, subjects] = await Promise.all([getHomework(filters), getAcademicRecords('classes'), getAcademicRecords('subjects')]); setData(await homeworkWithLocalChanges(scope, await cacheHomework(scope, { items, classes, subjects }))); setError(''); return } const cached = await cachedHomework(scope); setData(await homeworkWithLocalChanges(scope, cached) || { items: [], classes: [], subjects: [] }); if (!cached) setError('Homework has not synchronized on this device yet.') } catch { const cached = await cachedHomework(scope); setData(await homeworkWithLocalChanges(scope, cached) || { items: [], classes: [], subjects: [] }); setError(cached ? '' : 'Homework could not be loaded.') } finally { setLoading(false) } }, [filters, isReachable, scope])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load, syncRevision])
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event) { event.preventDefault(); setError(''); setNotice(''); if (editing && !isReachable) { setError('Connect to the internet to edit existing homework.'); return } if (files.length && !isReachable) { setError('Connect to the internet to upload homework attachments.'); return } try { if (!isReachable) { if (!data.classes.length) { setError('Connect once to synchronize class and subject choices before creating homework offline.'); return } await queueHomework(scope, { ...form, school_class: Number(form.school_class), subject: form.subject ? Number(form.subject) : null }); setForm(blank()); setData(await homeworkWithLocalChanges(scope, await cachedHomework(scope))); await refresh?.(); setNotice('Homework saved locally. It will synchronize when you reconnect.'); return } const body = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value !== '') body.append(key, value) }); files.forEach((file) => body.append('uploaded_attachments', file)); await saveHomework(body, editing?.id); setForm(blank()); setFiles([]); setEditing(null); await load() } catch (requestError) { setError(message(requestError)) } }
  function edit(item) { if (String(item.id).startsWith('local:')) return; setEditing(item); setForm({ title: item.title, instructions: item.instructions, school_class: String(item.school_class), subject: item.subject ? String(item.subject) : '', date_assigned: item.date_assigned, due_date: item.due_date, status: item.status }); setFiles([]) }
  async function retry(operation) { await updateOperation(operation.id, { status: 'pending', retryCount: 0, failureCategory: null, failureMessage: null }); await refresh?.(); if (isReachable) await syncNow(true) }
  async function discard(operation) { await discardOperation(operation.id); await refresh?.(); await load(); setNotice('Local homework discarded.') }
  return <main className="student-page"><header className="student-page-header"><div><Link to="/school/academics" className="dashboard-link">Back to Academics</Link><h1>Homework</h1><p>Create drafts or publish class-based homework.</p></div></header>{!isReachable && data.cachedAt && <p className="inventory-cache-notice">Offline — showing homework from last sync: {new Date(data.cachedAt).toLocaleString()}.</p>}{error && <p className="form-error">{error}</p>}{notice && <p className="communication-notice">{notice}</p>}{issues.length > 0 && <section className="inventory-sync-issues"><h2>Homework sync issues</h2>{issues.map((operation) => <div key={operation.id}><strong>{operation.payload.title}</strong><p>{operation.failureMessage}</p><button type="button" className="inline-button" onClick={() => retry(operation)}>Retry</button><button type="button" className="text-button" onClick={() => discard(operation)}>Discard local draft</button></div>)}</section>}
    <form className="student-form academic-form" onSubmit={submit}><h2>{editing ? 'Edit Homework' : 'Add Homework'}</h2><div className="form-columns"><label>Title<input required maxLength="200" value={form.title} onChange={(e) => set('title', e.target.value)} /></label><label>Class<select required value={form.school_class} onChange={(e) => set('school_class', e.target.value)}><option value="">Choose class</option>{data.classes.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Subject (optional)<select value={form.subject} onChange={(e) => set('subject', e.target.value)}><option value="">No subject</option>{data.subjects.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label>Instructions<textarea rows="5" value={form.instructions} onChange={(e) => set('instructions', e.target.value)} /></label><div className="form-columns"><label>Assigned<input required type="date" value={form.date_assigned} onChange={(e) => set('date_assigned', e.target.value)} /></label><label>Due<input required type="date" min={form.date_assigned} value={form.due_date} onChange={(e) => set('due_date', e.target.value)} /></label><label>Status<select value={form.status} onChange={(e) => set('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label></div><label>Attachments <span className="field-help">Online only; files are never queued.</span><input type="file" multiple accept=".pdf,.docx,.jpg,.jpeg,.png" onChange={(e) => setFiles(Array.from(e.target.files))} /></label><div className="settings-actions"><button>{editing ? 'Save Changes' : 'Save Homework'}</button>{editing && <button type="button" className="secondary-button" onClick={() => { setEditing(null); setForm(blank()); setFiles([]) }}>Cancel</button>}</div></form>
    {loading ? <div className="student-state">Loading homework…</div> : data.items.length ? <div className="history-list">{data.items.map((item) => <div key={item.id}><span><strong>{item.title}</strong> · {item.class_name} · {item.subject_name || 'General'} · {item.status} {item.syncStatus && '· Pending sync'}<br /><small>Assigned {item.date_assigned} · Due {item.due_date}</small><br />{item.instructions}{item.attachments.map((a) => <button key={a.id} className="inline-button" onClick={() => downloadHomeworkAttachment('school', item.id, a)}>Download {a.original_name}</button>)}</span><span>{!String(item.id).startsWith('local:') && <button className="inline-button" onClick={() => edit(item)}>Edit</button>}</span></div>)}</div> : <div className="student-state">No homework matches the current filters.</div>}</main>
}
