import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { deleteHomework, downloadHomeworkAttachment, getHomework, removeHomeworkAttachment, saveHomework } from '../api/homework'
import { getAcademicRecords } from '../api/academics'

const empty = { title: '', instructions: '', school_class: '', subject: '', date_assigned: new Date().toISOString().slice(0, 10), due_date: '', status: 'draft' }
const message = (error) => Object.values(error?.data || {}).flat().join(' ') || 'The homework could not be saved.'

export default function HomeworkPage() {
  const [items, setItems] = useState([]); const [classes, setClasses] = useState([]); const [subjects, setSubjects] = useState([])
  const [form, setForm] = useState(empty); const [files, setFiles] = useState([]); const [editing, setEditing] = useState(null); const [filters, setFilters] = useState({ school_class: '', subject: '', due_date: '', status: '' })
  const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load() { try { setItems(await getHomework(filters)); setError('') } catch { setError('Homework could not be loaded.') } finally { setLoading(false) } }
  useEffect(() => { Promise.all([getAcademicRecords('classes'), getAcademicRecords('subjects')]).then(([c, s]) => { setClasses(c); setSubjects(s) }).catch(() => setError('Class and subject choices could not be loaded.')) }, [])
  useEffect(() => { getHomework(filters).then((values) => { setItems(values); setError('') }).catch(() => setError('Homework could not be loaded.')).finally(() => setLoading(false)) }, [filters])
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event) { event.preventDefault(); setError(''); const data = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value !== '') data.append(key, value) }); files.forEach((file) => data.append('uploaded_attachments', file)); try { await saveHomework(data, editing?.id); setForm(empty); setFiles([]); setEditing(null); await load() } catch (requestError) { setError(message(requestError)) } }
  function edit(item) { setEditing(item); setForm({ title: item.title, instructions: item.instructions, school_class: String(item.school_class), subject: item.subject ? String(item.subject) : '', date_assigned: item.date_assigned, due_date: item.due_date, status: item.status }); setFiles([]); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  async function remove(item) { if (window.confirm(`Delete “${item.title}”?`)) { try { await deleteHomework(item.id); await load() } catch { setError('Homework could not be deleted.') } } }
  return <main className="student-page"><header className="student-page-header"><div><Link to="/school/academics" className="dashboard-link">Back to Academics</Link><h1>Homework</h1><p>Create drafts or publish class-based homework with up to five protected attachments.</p></div></header>
    <form className="student-form academic-form" onSubmit={submit}><h2>{editing ? 'Edit Homework' : 'Add Homework'}</h2><div className="form-columns"><label>Title<input required maxLength="200" value={form.title} onChange={(e) => set('title', e.target.value)} /></label><label>Class<select required value={form.school_class} onChange={(e) => set('school_class', e.target.value)}><option value="">Choose class</option>{classes.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Subject (optional)<select value={form.subject} onChange={(e) => set('subject', e.target.value)}><option value="">No subject</option>{subjects.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label>Instructions<textarea rows="5" value={form.instructions} onChange={(e) => set('instructions', e.target.value)} /></label><div className="form-columns"><label>Assigned<input required type="date" value={form.date_assigned} onChange={(e) => set('date_assigned', e.target.value)} /></label><label>Due<input required type="date" min={form.date_assigned} value={form.due_date} onChange={(e) => set('due_date', e.target.value)} /></label><label>Status<select value={form.status} onChange={(e) => set('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label></div><label>Attachments <span className="field-help">PDF, DOCX, JPG, JPEG, or PNG; 10 MB each; five total.</span><input type="file" multiple accept=".pdf,.docx,.jpg,.jpeg,.png" onChange={(e) => setFiles(Array.from(e.target.files))} /></label>{editing?.attachments?.length > 0 && <div className="history-list">{editing.attachments.map((a) => <div key={a.id}><span>{a.original_name}</span><button type="button" className="text-button" onClick={async () => { await removeHomeworkAttachment(editing.id, a.id); const next = { ...editing, attachments: editing.attachments.filter((x) => x.id !== a.id) }; setEditing(next); await load() }}>Remove</button></div>)}</div>}{error && <p className="form-error">{error}</p>}<div className="settings-actions"><button>{editing ? 'Save Changes' : 'Save Homework'}</button>{editing && <button type="button" className="secondary-button" onClick={() => { setEditing(null); setForm(empty); setFiles([]) }}>Cancel</button>}</div></form>
    <div className="academic-filters"><label>Class<select value={filters.school_class} onChange={(e) => setFilters({ ...filters, school_class: e.target.value })}><option value="">All</option>{classes.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Subject<select value={filters.subject} onChange={(e) => setFilters({ ...filters, subject: e.target.value })}><option value="">All</option>{subjects.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Due date<input type="date" value={filters.due_date} onChange={(e) => setFilters({ ...filters, due_date: e.target.value })} /></label><label>Status<select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All</option><option value="draft">Draft</option><option value="published">Published</option></select></label></div>
    {loading ? <div className="student-state">Loading homework…</div> : items.length ? <div className="history-list">{items.map((item) => <div key={item.id}><span><strong>{item.title}</strong> · {item.class_name} · {item.subject_name || 'General'} · {item.status}<br /><small>Assigned {item.date_assigned} · Due {item.due_date}</small><br />{item.instructions}{item.attachments.map((a) => <button key={a.id} className="inline-button" onClick={() => downloadHomeworkAttachment('school', item.id, a)}>Download {a.original_name}</button>)}</span><span><button className="inline-button" onClick={() => edit(item)}>Edit</button><button className="text-button" onClick={() => remove(item)}>Delete</button></span></div>)}</div> : <div className="student-state">No homework matches the current filters.</div>}</main>
}
