import { useEffect, useMemo, useState } from 'react'
import { apiClient } from '../api/client'
import { downloadReceiptPdf, getParentStudentFinance } from '../api/finance'
import { getParentCommunicationPreference, getParentNotifications, markNotificationRead, updateParentCommunicationPreference } from '../api/communication'

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
const money = (currency, value) => `${currency} ${new Intl.NumberFormat(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value || 0)}`

export default function ParentDashboard() {
  const [students, setStudents] = useState([]); const [selected, setSelected] = useState(''); const [entries, setEntries] = useState([]); const [finance, setFinance] = useState(null)
  const [notifications, setNotifications] = useState([]); const [preference, setPreference] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([apiClient('/parent/students/'), getParentNotifications(), getParentCommunicationPreference()]).then(([items, notices, pref]) => { setStudents(items); setSelected(items[0]?.id ? String(items[0].id) : ''); setNotifications(notices); setPreference(pref) }).catch(() => setError('We could not load your parent portal.')).finally(() => setLoading(false)) }, [])
  useEffect(() => { if (selected) { apiClient(`/parent/students/${selected}/timetable/`).then(setEntries).catch(() => setError('We could not load this class timetable.')); getParentStudentFinance(selected).then(setFinance).catch(() => setError('We could not load this child’s finance information.')) } }, [selected])
  const slots = useMemo(() => Array.from(new Set(entries.map((entry) => `${entry.start_time} – ${entry.end_time}`))).sort(), [entries])
  const at = (slot, day) => entries.find((entry) => `${entry.start_time} – ${entry.end_time}` === slot && entry.day_of_week === day)
  const read = async (id) => { try { const notice = await markNotificationRead(id); setNotifications((items) => items.map((item) => item.id === id ? notice : item)) } catch { setError('That notification could not be updated.') } }
  const savePreference = async (event) => { event.preventDefault(); try { setPreference(await updateParentCommunicationPreference(preference)) } catch { setError('Your WhatsApp preference could not be saved. Use an international number beginning with + when opting in.') } }
  if (loading) return <main className="school-profile-state">Loading your children…</main>
  return <main className="student-page"><header className="student-page-header"><div><h1>Parent Portal</h1><p>Read-only child timetable, finance, and communication information.</p></div></header>{error && <p className="form-error">{error}</p>}
    <section className="profile-section"><h2>Notifications</h2>{notifications.length ? <div className="history-list">{notifications.map((notice) => <div key={notice.id}><span><strong>{notice.title}</strong><br />{notice.message}{notice.student_name ? ` · ${notice.student_name}` : ''}<br /><small>{new Date(notice.created_at).toLocaleString()}</small></span>{!notice.is_read && <button className="inline-button" onClick={() => read(notice.id)}>Mark read</button>}</div>)}</div> : <p className="muted-copy">No notifications are available.</p>}</section>
    {preference && <section className="profile-section"><h2>WhatsApp communication preference</h2><form className="student-form communication-form" onSubmit={savePreference}><label>Status<select value={preference.whatsapp_status} onChange={(event) => setPreference((item) => ({ ...item, whatsapp_status: event.target.value }))}><option value="not_configured">Not configured</option><option value="opted_in">Opted in</option><option value="opted_out">Opted out</option></select></label><label>WhatsApp number <span className="field-help">Use international format, for example +263771234567.</span><input value={preference.whatsapp_phone} onChange={(event) => setPreference((item) => ({ ...item, whatsapp_phone: event.target.value }))} /></label><button type="submit">Save preference</button></form></section>}
    {students.length ? <><section className="profile-section"><label className="timetable-selector">Child<select value={selected} onChange={(e) => setSelected(e.target.value)}>{students.map((x) => <option key={x.id} value={x.id}>{x.display_name} · {x.class_name}</option>)}</select></label></section>{finance && <><section className="finance-summary"><div><span>Total Charges</span><strong>{money(finance.currency, finance.total_charges)}</strong></div><div><span>Total Payments</span><strong>{money(finance.currency, finance.total_payments)}</strong></div><div><span>Outstanding Balance</span><strong>{money(finance.currency, finance.outstanding_balance)}</strong></div></section><section className="profile-section"><h2>Payments & Receipts</h2>{finance.payments.length ? <div className="history-list">{finance.payments.map((payment) => <div key={payment.id}><strong>{money(payment.currency, payment.amount)} · {payment.fee_name}{payment.is_reversed ? ' · Reversed' : ''}</strong><span>{new Date(payment.paid_at).toLocaleString()} · {payment.method}</span></div>)}</div> : <p className="muted-copy">No payments are available for this child.</p>}{finance.receipts.map((receipt) => <div className="history-list" key={receipt.id}><div><strong>{receipt.receipt_number}{receipt.is_reversed ? ' · Reversed' : ''}</strong><button className="inline-button" onClick={() => downloadReceiptPdf(receipt.id, true)}>Download Receipt</button></div></div>)}</section></>}<section className="profile-section"><h2>Class Timetable</h2><div className="student-table-wrap"><table className="student-table"><thead><tr><th>Time</th>{days.map((day) => <th key={day}>{day}</th>)}</tr></thead><tbody>{slots.length ? slots.map((slot) => <tr key={slot}><th>{slot}</th>{days.map((day) => <td key={day}>{at(slot, day)?.display_label || ''}</td>)}</tr>) : <tr><td colSpan="6" className="empty-cell">No timetable entries are available.</td></tr>}</tbody></table></div></section></> : <div className="student-state">No children are currently linked to this account.</div>}</main>
}
