# Generated by Django 6.1 on 2026-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_logo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentenrollment',
            name='one_enrollment_per_student_per_year',
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('left_on__isnull', True)), fields=('student',), name='one_open_enrollment_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('left_on__isnull', True), ('left_on__gte', models.F('enrolled_on')), _connector='OR'), name='enrollment_left_on_not_before_start'),
        ),
    ]
