# Generated by Django 6.1 on 2026-08-14 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fee_charge_month_fee_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='core.student'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('all_parents', 'All parents'), ('class', 'Specific class'), ('student', 'Specific student'), ('parent', 'Specific parent')], max_length=20)),
                ('channels', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='core.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='core.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='core.schoolclass')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('whatsapp', 'WhatsApp')], max_length=12)),
                ('event_type', models.CharField(choices=[('announcement', 'Announcement'), ('payment_receipt', 'Payment receipt'), ('fee_reminder', 'Fee reminder'), ('report_card_available', 'Report card available')], max_length=30)),
                ('template_key', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.announcement')),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_message', to='core.notification')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_messages', to='core.parent')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_messages', to='core.receipt')),
                ('report_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_messages', to='core.reportcard')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_messages', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_messages', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='ParentCommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_status', models.CharField(choices=[('not_configured', 'Not configured'), ('opted_in', 'Opted in'), ('opted_out', 'Opted out')], default='not_configured', max_length=20)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=30)),
                ('opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('consent_source', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='communication_preference', to='core.parent')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('payment_receipt_notifications_enabled', models.BooleanField(default=True)),
                ('fee_reminders_enabled', models.BooleanField(default=True)),
                ('report_card_notifications_enabled', models.BooleanField(default=True)),
                ('whatsapp_announcements_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='communication_settings', to='core.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['school', 'status', 'created_at'], name='core_announ_school__577ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['school', 'status', 'created_at'], name='core_commun_school__4dd1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['channel', 'status', 'claimed_at'], name='core_commun_channel_bf3c82_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['parent', 'created_at'], name='core_commun_parent__cd443e_idx'),
        ),
    ]
