# Generated by Django 6.1 on 2026-08-14 10:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_audit_and_demo_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('salaries', 'Salaries'), ('maintenance', 'Maintenance'), ('stationery', 'Stationery'), ('rent', 'Rent'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(max_length=3)),
                ('payment_method', models.CharField(max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.school')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['school', 'expense_date'], name='core_expens_school__b9a61f_idx')],
            },
        ),
    ]
