# Generated by Django 6.1 on 2026-08-15 13:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_homework_homeworkattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkattachment',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=core.models.homework_attachment_expiry),
        ),
    ]
