# Generated by Django 6.1 on 2026-09-20 04:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_homeworkattachment_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_categories', to='core.school')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='each', max_length=40)),
                ('minimum_stock_level', models.PositiveIntegerField(default=0)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('storage_location', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.inventorycategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='core.school')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='core.inventoryitem')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('restock', 'Restock'), ('issued', 'Issued'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('adjustment', 'Adjustment'), ('returned', 'Returned')], max_length=20)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.inventoryitem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_movements', to='core.school')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.inventoryvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorycategory',
            index=models.Index(fields=['school', 'is_active'], name='core_invent_school__afbd3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_inventory_category_per_school'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['school', 'category', 'is_active'], name='core_invent_school__c9c94b_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_inventory_item_per_school'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('school', 'code'), name='unique_inventory_item_code_per_school'),
        ),
        migrations.AddIndex(
            model_name='inventoryvariant',
            index=models.Index(fields=['item', 'is_active'], name='core_invent_item_id_586fb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryvariant',
            constraint=models.UniqueConstraint(fields=('item', 'name'), name='unique_inventory_variant_per_item'),
        ),
        migrations.AddConstraint(
            model_name='inventoryvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('item', 'code'), name='unique_inventory_variant_code_per_item'),
        ),
        migrations.AddIndex(
            model_name='inventorystockmovement',
            index=models.Index(fields=['school', 'created_at'], name='core_invent_school__62102a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockmovement',
            index=models.Index(fields=['item', 'variant', 'created_at'], name='core_invent_item_id_5fd436_idx'),
        ),
    ]
