# Generated by Django 6.1 on 2026-09-20 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_inventorycategory_inventoryitem_inventoryvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'actor', 'created_at'], name='core_idempo_school__171fab_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'actor', 'operation_id'), name='unique_idempotency_operation_per_actor_school')],
            },
        ),
    ]
