# Generated by Django 6.1 on 2026-09-20 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_idempotencyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.academicyear')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.studentenrollment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.term')),
            ],
            options={
                'ordering': ['attendance_date', 'enrollment__student__last_name', 'enrollment__student__first_name', 'id'],
                'indexes': [models.Index(fields=['school', 'attendance_date'], name='core_attend_school__b7d24b_idx'), models.Index(fields=['term', 'attendance_date'], name='core_attend_term_id_48ed26_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'term', 'attendance_date'), name='unique_attendance_enrollment_term_date')],
            },
        ),
    ]
