# Generated by Django 6.1 on 2026-09-20 09:51

from django.db import migrations, models


def preserve_legacy_inactive_schools(apps, schema_editor):
    School = apps.get_model('core', 'School')
    School.objects.filter(is_active=False).update(status='suspended')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attendance_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=12),
        ),
        migrations.RunPython(preserve_legacy_inactive_schools, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
