# Generated by Django 6.1 on 2026-10-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_school_status_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringfeetemplate',
            name='billing_method',
            field=models.CharField(choices=[('LEGACY', 'Legacy monthly'), ('MONTHLY', 'Monthly'), ('TERMLY', 'Termly'), ('ONE_OFF', 'One-off')], default='LEGACY', max_length=10),
        ),
        migrations.AddField(
            model_name='recurringfeetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringfeetemplate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.student'),
        ),
        migrations.AddField(
            model_name='recurringfeetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
