# Generated by Django 6.1 on 2026-10-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_recurringfeetemplate_billing_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='period_sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(condition=models.Q(('period_sequence__isnull', False)), fields=('recurring_template', 'period_sequence'), name='unique_fee_structure_period'),
        ),
    ]
