# Generated by Django 6.1 on 2026-10-05 18:58

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_fee_period_sequence_fee_unique_fee_structure_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_timetable_class_period',
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='classes',
            field=models.ManyToManyField(related_name='timetables', to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='core.school'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='core.term'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.timetable'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('school_class', 'academic_year', 'term', 'day_of_week', 'start_time', 'end_time'), name='unique_timetable_class_period'),
        ),
    ]
