# Generated by Django 6.1 on 2026-10-06 10:42

from django.db import migrations, models


def classify_existing(apps, schema_editor):
    Timetable = apps.get_model('core', 'Timetable')
    for plan in Timetable.objects.all().iterator():
        if plan.classes.count() == 1:
            Timetable.objects.filter(pk=plan.pk).update(scope='SINGLE')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_copy_legacy_timetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='scope',
            field=models.CharField(choices=[('SINGLE', 'One Class'), ('MULTIPLE', 'Multiple Classes'), ('WHOLE_SCHOOL', 'Whole School')], default='MULTIPLE', max_length=12),
        ),
        migrations.RunPython(classify_existing, migrations.RunPython.noop),
    ]
